### ISSUE TITLE
The FeatureForm application prepared as a sample does not start.

### ISSUE THREAD

**Issue by EJ-T-Murata** [Esri/arcgis-maps-sdk-kotlin-toolkit#451]
Hello all,

We checked the FeatureForm application prepared in this repository in Android Studio. Although the application compiles/builds, it crashes immediately after launching.
Could you please check if it works?

**Comment by rchintapalli** [comment]
It seems to run fine for us. Do you see any messages/stack trace in the logs when it crashed?

**Comment by EJ-T-Murata** [comment]
Thanks for the reply. I have confirmed that it works fine in my environment.
I confirmed this problem about two months ago with version 200.4, so it may have been fixed with the release of 200.5.
![Screenshot_20240805_105709_FeatureFormsApp](https://github.com/user-attachments/assets/dd7e8b9c-ee5a-4b79-ae43-0f5195be21ae)
