### ISSUE TITLE
Use Compass in android view system

### ISSUE THREAD

**Issue by padmalcom** [Esri/arcgis-maps-sdk-kotlin-toolkit#504]
Hi, our app is still partially based on android view system and not yet fully migrated to compose. Is it possible to define the compass composable in an xml?

**Comment by rchintapalli** [comment]
Technically, it should be possible using the ComposeView, but haven't tried it myself. Here is how Android recommends using compose in views
https://developer.android.com/develop/ui/compose/migrate/interoperability-apis/compose-in-views

**Comment by nishankhadka09** [comment]
Declare a composable view in the xml 
  <androidx.compose.ui.platform.ComposeView
        android:layout_width="40dp"
        android:layout_height="40dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
      " />



then you can do something like this:

```
binding.viewCompass.apply {
            // Dispose of the Composition when the view's LifecycleOwner
            // is destroyed
            setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)
            setContent {
                // In Compose world
                val rotation = mapView.mapRotation.collectAsState()
                val scope = rememberCoroutineScope()
                AppTheme {
                    Compass(rotation.value, autoHide = false, onClick = {
                        scope.launch {
                            mapView.setViewpointRotation(0.0)
                        }
                    })
                }
            }
        }
```
